export const QualificationSteps = {
    START: 0,
    INCOME_QUALIFICATIONS: 1,
    GOVERNMENT_HELP: 2,
    AFFORD_RENT: 3,
    UNSAFE_LIVING_CONDITIONS: 4,
    ATTEMPTING_TO_PAY: 5,
    HIGH_COVID_RATE: 6,
    QUALIFIED: 7,
    FINAL_STEP: 7
}

export const LetterBuilderSteps = {
    FIRST_STEP: 1,
    PERSONAL_INFO: 1,
    LANDLORD_INFO: 2,
    PREVIEW_LETTER: 3,
    SIGNATURE: 4,
    DOWNLOAD_LETTER: 5,
    FINAL_STEP: 3,
}
